export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_UPDATE_PROFILE_SUCCESS = "GET_UPDATE_PROFILE_SUCCESS";
export const GET_UPDATE_PROFILE_FAIL = "GET_UPDATE_PROFILE_FAIL";